import type { Meta, StoryObj } from '@storybook/react';
import { ClientDashboard } from './ClientDashboard';
import { ClientDashboardCase } from './ClientDashboardCard';

const meta: Meta<typeof ClientDashboard> = {
  title: 'Pages/Client/Client Dashboard',
  component: ClientDashboard,
  parameters: {
    layout: 'fullscreen',
  },
};

export default meta;
type Story = StoryObj<typeof ClientDashboard>;

const menuItems = [
  { label: 'Offer Accepted' },
  { label: 'Final Offer Received, waiting on lien sheet' },
  { label: 'Final Offer Received, lien sheet complete' },
  { label: 'Awaiting Settlement Hearing' },
  { label: 'Finished Case (Archive It)' },
  { label: 'BP Received' },
  { label: 'BP Sent Via Mail' },
  { label: 'Blank Release' },
  { label: 'Ordered/Waiting on Old Medical' },
  { label: 'No Offer 30+' },
  { label: 'Awaiting Mediation' },
  { label: 'Referred Case' },
  { label: 'Respond' },
  { label: 'Treating & No medical ordered yet' },
  { label: 'Finished Treating/ RTS & Awaiting' },
  { label: 'Finished Treating/ RTS & All Medical' },
  { label: 'RTS/All Medical Received' },
  { label: 'Sent to Demand Writer' },
  { label: 'Liability Demand Sent' },
  { label: 'UM Demand Sent' },
  { label: 'UIM Demand Sent' },
  { label: '30 Day Extension Given to Adjuster' },
  { label: 'Signed Release' },
  { label: 'Check Pending' },
]

const sampleCases: ClientDashboardCase[] = [
  {
    id: '1',
    caseNumber: '#2025-003',
    status: {
      text: 'Final Offer Received, waiting on lien sheet',
      color: 'var(--success)',
    },
    clientName: 'Martin, Samuel',
    primaryPhone: '(213) 987-6543',
    momsPhone: '(213) 987-6555',
    email: 'samuel.martin@email.com',
    casePlan: 'Response framework for intersection incident resolution',
    bigPolicy: true,
    bigInjury: false,
    injuryDescription: 'Wrist fracture, elbow sprain',
    clientStatusDetails: 'Pending orthopedic review for ongoing treatment.',
    lorSent: [
      { date: '1/10/25', event: 'MedPay - Geico', status: 'Sarah Johnson Policy' },
      { date: '1/15/25', event: 'UIM - State Farm', status: 'John Smith Policy' },
      { date: '1/20/25', event: 'Demand Sent', status: 'Negotiating w/ Geico' },
      { date: '2/5/25', event: 'Offer Received', status: 'Under Review' },
      { date: '2/15/25', event: 'Check Received', status: 'Deposited' }
    ],
    medRecsOrdered: {
      someOrdered: true,
      allOrdered: false,
      allOrderedDate: '3/15/25'
    },
    liabilityLimits: {
      wasInCar: true,
      insurances: ['Farmers - $25k', 'State Farm - $50k'],
      UmbrellaExcess: 'Injuries not large enough'
    },
    clientUIMlimits: 'Mercury: $50,000',
    residentUMUIMLimits: 'The Hartford: $500,000 (Stacked)',
    medpay: 'No',
    atFaultDriverOtherPolicies: false,
    subroSetup: 'No',
    wageLoss: '$7,200',
    demandSentStatus: '4/5/25 - Demand for expert opinions',
    settlementAcceptedRelease: '7/17/25',
    checkReceived: '7/17/25',
    caseAge: 178,
    billingPacketSent: 'July 1, 2025',
    policyReportOrdered: 'July 10, 2025',
    totalCurrentBills: '$1,246',
    menuItems: menuItems,
  },
  {
    id: '2',
    caseNumber: '#2025-003',
    status: {
      text: 'Final Offer Received, lien sheet complete',
      color: 'var(--success)',
    },
    clientName: 'Lee, Isabella',
    primaryPhone: '(213) 987-6543',
    momsPhone: '(213) 555-8901',
    email: 'isabella.lee@email.com',
    casePlan: 'Action framework for intersection collision case',
    bigPolicy: true,
    bigInjury: false,
    injuryDescription: 'Fractured wrist, elbow strain',
    clientStatusDetails: 'Awaiting orthopedic insights for case management.',
    lorSent: [
      { date: '2/15/25', event: 'UIM - State Farm', status: 'John Smith Policy' },
      { date: '2/20/25', event: 'Med Recs Ordered', status: 'Complete' },
      { date: '2/25/25', event: 'Demand Sent', status: 'Negotiating w/ State Farm' },
      { date: '3/10/25', event: 'Offer Accepted', status: 'Settlement Reached' },
      { date: '3/15/25', event: 'Check Received', status: 'Deposited' }
    ], 
    medRecsOrdered: {
      someOrdered: true,
      allOrdered: true,
      allOrderedDate: '5/1/25'
    },
    liabilityLimits: {
      wasInCar: true,
      insurances: ['AIG - $50k'],
      UmbrellaExcess: 'Yes - $1M umbrella'
    },
    clientUIMlimits: 'Mercury: $50,000',
    residentUMUIMLimits: 'AIG: $500,000 (Stacked)',
    medpay: 'No',
    atFaultDriverOtherPolicies: false,
    subroSetup: 'No',
    wageLoss: '$6,300',
    demandSentStatus: '4/5/25 - Demand for rehabilitation records',
    settlementAcceptedRelease: '7/15/25',
    checkReceived: '6/15/25',
    caseAge: 148,
    billingPacketSent: 'July 1, 2025',
    policyReportOrdered: 'July 10, 2025',
    totalCurrentBills: '$1,246',
    menuItems: menuItems,
  },
  {
    id: '3',
    caseNumber: '#2025-003',
    status: {
      text: 'Awaiting Settlement Hearing',
      color: 'var(--success)',
    },
    clientName: 'Perez, Elijah',
    primaryPhone: '(213) 987-6543',
    momsPhone: '(213) 555-4567',
    email: 'elijah.perez@email.com',
    casePlan: 'Incident action plan for intersection accident',
    bigPolicy: true,
    bigInjury: false,
    injuryDescription: 'Wrist fracture, elbow injury',
    clientStatusDetails: 'Pending orthopedic evaluation for treatment adjustments.',
    lorSent: [
      { date: '3/20/25', event: 'MedPay - Allstate', status: 'Mike Wilson Policy' },
      { date: '3/25/25', event: 'Med Recs Ordered', status: 'Partial' },
      { date: '4/1/25', event: 'Demand Sent', status: 'Awaiting Response' },
      { date: '4/15/25', event: 'Offer Received', status: 'Under Review' }
    ],
    medRecsOrdered: {
      someOrdered: true,
      allOrdered: true,
      allOrderedDate: '5/1/25'
    },
    liabilityLimits: {
      wasInCar: true,
      insurances: ['Cincinnati - $100k'],
      UmbrellaExcess: 'No'
    },
    clientUIMlimits: 'Mercury: $50,000',
    residentUMUIMLimits: 'Cincinnati Insurance: $500,000 (Stacked)',
    medpay: 'No',
    atFaultDriverOtherPolicies: false,
    subroSetup: 'No',
    wageLoss: '$8,800',
    demandSentStatus: '4/5/25 - Demand for medical history sent to Primary Care.',
    settlementAcceptedRelease: '7/17/25',
    checkReceived: '6/15/25',
    caseAge: 142,
    billingPacketSent: 'July 1, 2025',
    policyReportOrdered: 'July 10, 2025',
    totalCurrentBills: '$1,246',
    menuItems: menuItems,
  },
  {
    id: '4',
    caseNumber: '#2025-003',
    status: {
      text: 'Finished Case (Archive It)',
      color: 'var(--success)',
    },
    clientName: 'Thompson, Scarlett',
    primaryPhone: '(213) 987-6543',
    momsPhone: '(213) 222-2323',
    email: 'scarlett.thompson@example.com',
    casePlan: 'Comprehensive strategy for intersection incident management',
    bigPolicy: true,
    bigInjury: false,
    injuryDescription: 'Fractured wrist, elbow sprain',
    clientStatusDetails: 'Awaiting orthopedic feedback for case follow-up.',
    lorSent: [
      { date: '4/5/25', event: 'UIM - Farmers', status: 'Lisa Brown Policy' },
      { date: '4/10/25', event: 'Med Recs Ordered', status: 'Complete' },
      { date: '4/15/25', event: 'Demand Sent', status: 'Negotiating w/ Farmers' },
      { date: '5/1/25', event: 'Offer Accepted', status: 'Settlement Reached' },
      { date: '5/5/25', event: 'Check Received', status: 'Deposited' }
    ],
    medRecsOrdered: {
      someOrdered: true,
      allOrdered: true,
      allOrderedDate: '5/1/25'
    },
    liabilityLimits: {
      wasInCar: false,
      insurances: ['Safeco - $25k'],
      UmbrellaExcess: 'Injury not severe enough'
    },
    clientUIMlimits: 'Mercury: $50,000',
    residentUMUIMLimits: 'Safeco: $500,000 (Stacked)',
    medpay: 'No',
    atFaultDriverOtherPolicies: false,
    subroSetup: 'No',
    wageLoss: '$9,100',
    demandSentStatus: '4/5/25 - Demand for treatment plans sent to Care Coordinator.',
    settlementAcceptedRelease: '7/17/25',
    checkReceived: '7/17/25',
    caseAge: 215,
    billingPacketSent: 'July 1, 2025',
    policyReportOrdered: 'July 10, 2025',
    totalCurrentBills: '$1,246',
    menuItems: menuItems,
  },
  {
    id: '5',
    caseNumber: '#2025-001',
    status: {
      text: 'BP Received',
      color: 'var(--primary-color)',
    },
    clientName: 'Brown, Mia',
    primaryPhone: '(618) 216 2917',
    momsPhone: '(618) 555-3456',
    email: 'mia.brown@email.com',
    casePlan: 'Auto accident in Pasadena',
    bigPolicy: true,
    bigInjury: false,
    injuryDescription: 'Whiplash, shoulder sprain',
    clientStatusDetails: '5/7/25 - 5/1/25 - Lorem Ipsum is sim',
    lorSent: [
      { date: '4/5/25', event: 'MedPay - OrthoCare' },
      { date: '4/7/25', event: 'UIM - Imaging Center' },
      { date: '4/10/25', event: 'Med Recs Ordered', status: 'Complete' },
      { date: '4/15/25', event: 'Demand Sent', status: 'Negotiating w/ State Farm' },
      { date: '4/20/25', event: 'Offer Accepted', status: 'Settlement Reached' },
      { date: '4/25/25', event: 'Check Received', status: 'Deposited' }
    ],
    medRecsOrdered: {
      someOrdered: true,
      allOrdered: true,
      allOrderedDate: '5/1/25'
    },
    liabilityLimits: {
      wasInCar: true,
      insurances: ['Allstate - $50k', 'Travelers - $100k'],
      UmbrellaExcess: 'Pending review'
    },
    clientUIMlimits: 'Geico: None',
    residentUMUIMLimits: 'Farmers: $250,000 (Stacked)',
    medpay: 'Medical $1,000',
    atFaultDriverOtherPolicies: false,
    subroSetup: 'No',
    wageLoss: '$4,200',
    demandSentStatus: '4/7/25 - Negotiating w/ State Farm',
    settlementAcceptedRelease: 'No',
    checkReceived: '4/15/25',
    caseAge: 87,
    billingPacketSent: 'July 1, 2025',
    policyReportOrdered: 'July 10, 2025',
    totalCurrentBills: '$1,246',
    menuItems: menuItems,
  },
  {
    id: '6',
    caseNumber: '#2025-002',
    status: {
      text: 'BP Sent Via Mail',
      color: 'var(--success)',
    },
    clientName: 'Garcia, Raj',
    primaryPhone: '(213) 555 8392',
    momsPhone: '(213) 555-7890',
    email: 'raj.garcia@email.com',
    casePlan: 'Rear-end freeway crash',
    bigPolicy: true,
    bigInjury: false,
    injuryDescription: 'Lower back strain',
    clientStatusDetails: 'Final med review completedCheck pending',
    lorSent: [
      { date: '1/5/25', event: 'UIM - Liberty Mutual', status: 'John Smith Policy' },
      { date: '1/10/25', event: 'Med Recs Ordered', status: 'Complete' },
      { date: '1/15/25', event: 'Demand Sent', status: 'Negotiating w/ Liberty Mutual' },
      { date: '2/1/25', event: 'Offer Accepted', status: 'Settlement Reached' },
      { date: '2/5/25', event: 'Check Received', status: 'Deposited' }
    ],
    medRecsOrdered: {
      someOrdered: true,
      allOrdered: true,
      allOrderedDate: '5/1/25'
    },
    liabilityLimits: {
      wasInCar: false,
      insurances: ['Progressive - $100k'],
      UmbrellaExcess: 'N/A'
    },
    clientUIMlimits: 'No UM',
    residentUMUIMLimits: 'Progressive: $50,000 (Single Policy)',
    medpay: 'Medical $2,000',
    atFaultDriverOtherPolicies: false,
    subroSetup: 'No',
    wageLoss: '$2,200',
    demandSentStatus: '4/5/25 - Offer accepted',
    settlementAcceptedRelease: '4/15/25',
    checkReceived: '4/15/25',
    caseAge: 112,
    billingPacketSent: 'July 1, 2025',
    policyReportOrdered: 'July 10, 2025',
    totalCurrentBills: '$1,246',
    menuItems: menuItems,
  },
  {
    id: '7',
    caseNumber: '#2025-003',
    status: {
      text: 'Awaiting Mediation',
      color: 'var(--orange)',
    },
    clientName: 'Moore, Aiden',
    primaryPhone: '(213) 987-6543',
    momsPhone: '(213) 555-2345',
    email: 'aiden.moore@email.com',
    casePlan: 'Incident management plan for intersection collision',
    bigPolicy: true,
    bigInjury: false,
    injuryDescription: 'Wrist fracture, elbow strain',
    clientStatusDetails: 'Pending orthopedic findings for further action.',
    lorSent: [
      { date: '5/12/25', event: 'MedPay - USAA', status: 'Robert Taylor Policy' },
      { date: '5/15/25', event: 'Med Recs Ordered', status: 'Partial' },
      { date: '5/20/25', event: 'Demand Sent', status: 'Awaiting Response' }
    ],
    medRecsOrdered: {
      someOrdered: true,
      allOrdered: true,
      allOrderedDate: '5/1/25'
    },
    liabilityLimits: {
      wasInCar: true,
      insurances: ['USAA - $25k'],
      UmbrellaExcess: 'Yes - $500k umbrella'
    },
    clientUIMlimits: 'Mercury: $50,000',
    residentUMUIMLimits: 'USAA: $500,000 (Stacked)',
    medpay: 'No',
    atFaultDriverOtherPolicies: false,
    subroSetup: 'No',
    wageLoss: '$8,600',
    demandSentStatus: '4/5/25 - Demand for insurance details',
    settlementAcceptedRelease: '7/17/25',
    checkReceived: '7/17/25',
    caseAge: 76,
    billingPacketSent: 'July 1, 2025',
    policyReportOrdered: 'July 10, 2025',
    totalCurrentBills: '$1,246',
    menuItems: menuItems,
  },
  {
    id: '8',
    caseNumber: '#2025-003',
    status: {
      text: 'Referred Case',
      color: 'var(--orange)',
    },
    clientName: 'Jackson, Chloe',
    primaryPhone: '(213) 987-6543',
    momsPhone: '(213) 555-6789',
    email: 'chloe.jackson@email.com',
    casePlan: 'Strategic plan for intersection accident case handling',
    bigPolicy: true,
    bigInjury: false,
    injuryDescription: 'Fractured wrist, elbow injury',
    clientStatusDetails: 'Awaiting orthopedic updates for case resolution.',
    lorSent: [
      { date: '6/8/25', event: 'UIM - Chubb', status: 'Maria Garcia Policy' },
      { date: '6/12/25', event: 'Med Recs Ordered', status: 'Complete' },
      { date: '6/18/25', event: 'Demand Sent', status: 'Negotiating w/ Chubb' },
      { date: '7/1/25', event: 'Offer Received', status: 'Under Review' }
    ],
    medRecsOrdered: {
      someOrdered: true,
      allOrdered: true,
      allOrderedDate: '5/1/25'
    },
    liabilityLimits: {
      wasInCar: true,
      insurances: ['Chubb - $250k', 'MetLife - $100k'],
      UmbrellaExcess: 'Yes - $2M umbrella'
    },
    clientUIMlimits: 'Mercury: $50,000',
    residentUMUIMLimits: 'Chubb: $500,000 (Stacked)',
    medpay: 'No',
    atFaultDriverOtherPolicies: false,
    subroSetup: 'No',
    wageLoss: '$5,900',
    demandSentStatus: '4/5/25 - Demand for medical evaluations',
    settlementAcceptedRelease: '7/15/25',
    checkReceived: '6/15/25',
    caseAge: 101,
    billingPacketSent: 'July 1, 2025',
    policyReportOrdered: 'July 10, 2025',
    totalCurrentBills: '$1,246',
    menuItems: menuItems,
  },
  {
    id: '9',
    caseNumber: '#2025-003',
    status: {
      text: 'Treating & No medical ordered yet',
      color: 'var(--orange)',
    },
    clientName: 'Smith, Olivia',
    primaryPhone: '(213) 987-6543',
    momsPhone: '(213) 555-3210',
    email: 'olivia.smith@email.com',
    casePlan: 'Sideswipe near intersection',
    bigPolicy: true,
    bigInjury: false,
    injuryDescription: 'Broken arm, shoulder sprain',
    clientStatusDetails: 'Awaiting orthopedic update',
    lorSent: [
      { date: '7/3/25', event: 'MedPay - GEICO', status: 'David Williams Policy' },
      { date: '7/8/25', event: 'Med Recs Ordered', status: 'Complete' },
      { date: '7/15/25', event: 'Demand Sent', status: 'Negotiating w/ GEICO' },
      { date: '7/25/25', event: 'Offer Accepted', status: 'Settlement Reached' },
      { date: '7/30/25', event: 'Check Received', status: 'Deposited' }
    ],
    medRecsOrdered: {
      someOrdered: true,
      allOrdered: true,
      allOrderedDate: '5/1/25'
    },
    liabilityLimits: {
      wasInCar: true,
      insurances: ['GEICO - $50k'],
      UmbrellaExcess: 'No'
    },
    clientUIMlimits: 'Mercury: $50,000',
    residentUMUIMLimits: 'GEICO: $300,000 (Stacked)',
    medpay: 'No',
    atFaultDriverOtherPolicies: false,
    subroSetup: 'No',
    wageLoss: '$7,400',
    demandSentStatus: '4/5/25 - Med review in progress',
    settlementAcceptedRelease: '7/15/25',
    checkReceived: '6/15/25',
    caseAge: 82,
    billingPacketSent: 'July 1, 2025',
    policyReportOrdered: 'July 10, 2025',
    totalCurrentBills: '$1,246',
    menuItems: menuItems,
  },
  {
    id: '10',
    caseNumber: '#2025-003',
    status: {
      text: 'Finished Treating/RTS & Awaiting',
      color: 'var(--orange)',
    },
    clientName: 'Johnson, Ava',
    primaryPhone: '(213) 987-6543',
    momsPhone: '(213) 555-9012',
    email: 'ava.johnson@email.com',
    casePlan: 'Action plan for intersection collision incident',
    bigPolicy: true,
    bigInjury: false,
    injuryDescription: 'Fractured wrist, elbow strain',
    clientStatusDetails: 'Awaiting orthopedic assessment for further updates.',
    lorSent: [
      { date: '8/15/25', event: 'UIM - Allied', status: 'Jennifer Davis Policy' },
      { date: '8/20/25', event: 'Med Recs Ordered', status: 'Partial' },
      { date: '8/25/25', event: 'Demand Sent', status: 'Awaiting Response' }
    ],
    medRecsOrdered: {
      someOrdered: true,
      allOrdered: true,
      allOrderedDate: '5/1/25'
    },
    liabilityLimits: {
      wasInCar: false,
      insurances: ['Allied - $100k'],
      UmbrellaExcess: 'Pending verification'
    },
    clientUIMlimits: 'Mercury: $50,000',
    residentUMUIMLimits: 'Allied Insurance: $500,000 (Stacked)',
    medpay: 'No',
    atFaultDriverOtherPolicies: false,
    subroSetup: 'No',
    wageLoss: '$8,250',
    demandSentStatus: '4/5/25 - Ongoing medical evaluation in progress',
    settlementAcceptedRelease: '7/15/25',
    checkReceived: '6/15/25',
    caseAge: 124,
    billingPacketSent: 'July 1, 2025',
    policyReportOrdered: 'July 10, 2025',
    totalCurrentBills: '$1,246',
    menuItems: menuItems,
  },
  {
    id: '12',
    caseNumber: '#2025-003',
    status: {
      text: 'RTS/All Medical Received',
      color: 'var(--success)',
    },
    clientName: 'Martinez, Zoe',
    primaryPhone: '(213) 987-6543',
    momsPhone: '(213) 555-5678',
    email: 'zoe.martinez@email.com',
    casePlan: 'Incident response plan for intersection crash',
    bigPolicy: true,
    bigInjury: false,
    injuryDescription: 'Wrist fracture, elbow injury',
    clientStatusDetails: 'Awaiting orthopedic feedback on treatment.',
    lorSent: [
      { date: '10/5/25', event: 'UIM - Progressive', status: 'Lisa Taylor Policy' },
      { date: '10/8/25', event: 'Med Recs Ordered', status: 'Complete' },
      { date: '10/12/25', event: 'Demand Sent', status: 'Negotiating w/ Progressive' },
      { date: '10/20/25', event: 'Offer Accepted', status: 'Settlement Reached' },
      { date: '10/25/25', event: 'Check Received', status: 'Deposited' }
    ],
    medRecsOrdered: {
      someOrdered: true,
      allOrdered: true,
      allOrderedDate: '5/1/25'
    },
    liabilityLimits: {
      wasInCar: true,
      insurances: ['Progressive - $50k'],
      UmbrellaExcess: 'No'
    },
    clientUIMlimits: 'Mercury: $50,000',
    residentUMUIMLimits: 'Progressive: $500,000 (Stacked)',
    medpay: 'No',
    atFaultDriverOtherPolicies: false,
    subroSetup: 'No',
    wageLoss: '$7,800',
    demandSentStatus: '4/5/25 - Demand for imaging results sent to Imaging Center.',
    settlementAcceptedRelease: '7/17/25',
    checkReceived: '7/17/25',
    caseAge: 163,
    billingPacketSent: 'July 1, 2025',
    policyReportOrdered: 'July 10, 2025',
    totalCurrentBills: '$1,246',
    menuItems: menuItems,
  },
  {
    id: '13',
    caseNumber: '#2025-003',
    status: {
      text: 'Ordered/Waiting on Old Medical',
      color: 'var(--success)',
    },
    clientName: 'Taylor, Grace',
    primaryPhone: '(213) 987-6543',
    momsPhone: '(213) 555-8765',
    email: 'grace.taylor@email.com',
    casePlan: 'Operational plan for intersection accident response',
    bigPolicy: true,
    bigInjury: false,
    injuryDescription: 'Fractured wrist, elbow injury',
    clientStatusDetails: 'Awaiting orthopedic input on recovery plan.',
    lorSent: [
      { date: '11/18/25', event: 'MedPay - Travelers', status: 'Robert Wilson Policy' },
      { date: '11/22/25', event: 'Med Recs Ordered', status: 'Partial' },
      { date: '11/28/25', event: 'Demand Sent', status: 'Awaiting Response' }
    ],
    medRecsOrdered: {
      someOrdered: true,
      allOrdered: true,
      allOrderedDate: '5/1/25'
    },
    liabilityLimits: {
      wasInCar: true,
      insurances: ['MetLife - $300k'],
      UmbrellaExcess: 'Yes - $3M umbrella'
    },
    clientUIMlimits: 'Mercury: $50,000',
    residentUMUIMLimits: 'MetLife: $500,000 (Stacked)',
    medpay: 'No',
    atFaultDriverOtherPolicies: false,
    subroSetup: 'No',
    wageLoss: '$6,500',
    demandSentStatus: '4/5/25 - Demand for accident report',
    settlementAcceptedRelease: '7/15/25',
    checkReceived: '6/15/25',
    caseAge: 88,
    billingPacketSent: 'July 1, 2025',
    policyReportOrdered: 'July 10, 2025',
    totalCurrentBills: '$1,246',
    menuItems: menuItems,
  },
  {
    id: '14',
    caseNumber: '#2025-003',
    status: {
      text: 'Sent to Demand Writer',
      color: 'var(--purple)',
    },
    clientName: 'Hernandez, Leo',
    primaryPhone: '(213) 987-6543',
    momsPhone: '(213) 555-1098',
    email: 'leo.hernandez@email.com',
    casePlan: 'Comprehensive plan for intersection accident management',
    bigPolicy: true,
    bigInjury: false,
    injuryDescription: 'Fractured wrist, elbow injury',
    clientStatusDetails: 'Pending orthopedic review for case progression.',
    lorSent: [
      { date: '12/2/25', event: 'UIM - Nationwide', status: 'Emma Lopez Policy' },
      { date: '12/5/25', event: 'Med Recs Ordered', status: 'Complete' },
      { date: '12/10/25', event: 'Demand Sent', status: 'Negotiating w/ Nationwide' },
      { date: '12/18/25', event: 'Offer Received', status: 'Under Review' }
    ],
    medRecsOrdered: {
      someOrdered: true,
      allOrdered: true,
      allOrderedDate: '5/1/25'
    },
    liabilityLimits: {
      wasInCar: false,
      insurances: ['Liberty Mutual - $50k'],
      UmbrellaExcess: 'Not applicable'
    },
    clientUIMlimits: 'Mercury: $50,000',
    residentUMUIMLimits: 'Liberty Mutual: $500,000 (Stacked)',
    medpay: 'No',
    atFaultDriverOtherPolicies: false,
    subroSetup: 'No',
    wageLoss: '$5,600',
    demandSentStatus: '4/5/25 - Demand for treatment notes MedCare.',
    settlementAcceptedRelease: '7/17/25',
    checkReceived: '7/17/25',
    caseAge: 221,
    billingPacketSent: 'July 1, 2025',
    policyReportOrdered: 'July 10, 2025',
    totalCurrentBills: '$1,246',
    menuItems: menuItems,
  },
  {
    id: '15',
    caseNumber: '#2025-003',
    status: {
      text: 'Liability Demand Sent',
      color: 'var(--purple)',
    },
    clientName: 'Lopez, Emma',
    primaryPhone: '(213) 987-6543',
    momsPhone: '(213) 555-7654',
    email: 'emma.lopez@email.com',
    casePlan: 'Detailed action plan for intersection incident resolution',
    bigPolicy: true,
    bigInjury: false,
    injuryDescription: 'Broken wrist, elbow sprain',
    clientStatusDetails: 'Awaiting orthopedic consultation outcomes.',
    lorSent: [
      { date: '1/8/25', event: 'MedPay - USAA', status: 'Noah Wilson Policy' },
      { date: '1/12/25', event: 'Med Recs Ordered', status: 'Complete' },
      { date: '1/18/25', event: 'Demand Sent', status: 'Negotiating w/ USAA' },
      { date: '1/25/25', event: 'Offer Accepted', status: 'Settlement Reached' },
      { date: '1/30/25', event: 'Check Received', status: 'Deposited' }
    ],
    medRecsOrdered: {
      someOrdered: true,
      allOrdered: true,
      allOrderedDate: '5/1/25'
    },
    liabilityLimits: {
      wasInCar: true,
      insurances: ['Farmers - $100k', 'Nationwide - $75k'],
      UmbrellaExcess: 'Yes - $500k umbrella'
    },
    clientUIMlimits: 'Mercury: $50,000',
    residentUMUIMLimits: 'Farmers Insurance: $500,000 (Stacked)',
    medpay: 'No',
    atFaultDriverOtherPolicies: false,
    subroSetup: 'No',
    wageLoss: '$9,300',
    demandSentStatus: '4/5/25 - Demand for physical therapy records sent to PT',
    settlementAcceptedRelease: '7/15/25',
    checkReceived: '6/15/25',
    caseAge: 113,
    billingPacketSent: 'July 1, 2025',
    policyReportOrdered: 'July 10, 2025',
    totalCurrentBills: '$1,246',
    menuItems: menuItems,
  },
  {
    id: '16',
    caseNumber: '#2025-003',
    status: {
      text: 'UM Demand Sent',
      color: 'var(--purple)',
    },
    clientName: 'Wilson, Noah',
    primaryPhone: '(213) 987-6543',
    momsPhone: '(213) 555-3987',
    email: 'noah.wilson@email.com',
    casePlan: 'Case strategy for intersection collision analysis',
    bigPolicy: true,
    bigInjury: false,
    injuryDescription: 'Wrist fracture, elbow strain',
    clientStatusDetails: 'Pending orthopedic insights for next steps.',
    lorSent: [
      { date: '2/14/25', event: 'UIM - Travelers', status: 'Lily Anderson Policy' },
      { date: '2/18/25', event: 'Med Recs Ordered', status: 'Partial' },
      { date: '2/22/25', event: 'Demand Sent', status: 'Awaiting Response' }
    ],
    medRecsOrdered: {
      someOrdered: true,
      allOrdered: true,
      allOrderedDate: '5/1/25'
    },
    liabilityLimits: {
      wasInCar: true,
      insurances: ['Nationwide - $250k'],
      UmbrellaExcess: 'Yes - $2M umbrella'
    },
    clientUIMlimits: 'Mercury: $50,000',
    residentUMUIMLimits: 'Nationwide: $500,000 (Stacked)',
    medpay: 'No',
    atFaultDriverOtherPolicies: false,
    subroSetup: 'No',
    wageLoss: '$4,750',
    demandSentStatus: '4/5/25 - Demand for follow-up consultations.',
    settlementAcceptedRelease: '7/15/25',
    checkReceived: '6/15/25',
    caseAge: 175,
    billingPacketSent: 'July 1, 2025',
    policyReportOrdered: 'July 10, 2025',
    totalCurrentBills: '$1,246',
    menuItems: menuItems,
  },
  {
    id: '17',
    caseNumber: '#2025-003',
    status: {
      text: 'UIM Demand Sent',
      color: 'var(--purple)',
    },
    clientName: 'Anderson, Lily',
    primaryPhone: '(213) 987-6543',
    momsPhone: '(213) 555-6540',
    email: 'lily.anderson@email.com',
    casePlan: 'Plan of action for intersection accident investigation',
    bigPolicy: true,
    bigInjury: false,
    injuryDescription: 'Fractured wrist, elbow sprain',
    clientStatusDetails: 'Awaiting orthopedic recommendations for treatment.',
    lorSent: [
      { date: '3/28/25', event: 'MedPay - American Family', status: 'Lucas Thomas Policy' },
      { date: '4/1/25', event: 'Med Recs Ordered', status: 'Complete' },
      { date: '4/5/25', event: 'Demand Sent', status: 'Negotiating w/ American Family' },
      { date: '4/12/25', event: 'Offer Received', status: 'Under Review' }
    ],
    medRecsOrdered: {
      someOrdered: true,
      allOrdered: true,
      allOrderedDate: '5/1/25'

    },
    liabilityLimits: {
      wasInCar: true,
      insurances: ['Travelers - $50k'],
      UmbrellaExcess: 'No'
    },
    clientUIMlimits: 'Mercury: $50,000',
    residentUMUIMLimits: 'Travelers: $500,000 (Stacked)',
    medpay: 'No',
    atFaultDriverOtherPolicies: false,
    subroSetup: 'No',
    wageLoss: '$8,100',
    demandSentStatus: '4/5/25 - Demand for billing statements',
    settlementAcceptedRelease: '7/17/25',
    checkReceived: '7/17/25',
    caseAge: 69,
    billingPacketSent: 'July 1, 2025',
    policyReportOrdered: 'July 10, 2025',
    totalCurrentBills: '$1,246',
    menuItems: menuItems,
  },
  {
    id: '18',
    caseNumber: '#2025-003',
    status: {
      text: '30 Day Extension Given to Adjuster',
      color: 'var(--purple)',
    },
    clientName: 'Thomas, Lucas',
    primaryPhone: '(213) 987-6543',
    momsPhone: '(213) 555-2109',
    email: 'lucas.thomas@email.com',
    casePlan: 'Tactical plan for handling intersection incident',
    bigPolicy: true,
    bigInjury: false,
    injuryDescription: 'Wrist fracture, elbow strain',
    clientStatusDetails: 'Pending orthopedic analysis for case status.',
    lorSent: [
      { date: '4/12/25', event: 'UIM - Liberty Mutual', status: 'Chris Lee Policy' },
      { date: '4/15/25', event: 'Med Recs Ordered', status: 'Partial' },
      { date: '4/20/25', event: 'Demand Sent', status: 'Awaiting Response' }
    ],
    medRecsOrdered: {
      someOrdered: true,
      allOrdered: true,
      allOrderedDate: '5/1/25'
    },
    liabilityLimits: {
      wasInCar: false,
      insurances: ['American Family - $100k'],
      UmbrellaExcess: 'Injuries not sufficient'
    },
    clientUIMlimits: 'Mercury: $50,000',
    residentUMUIMLimits: 'American Family: $500,000 (Stacked)',
    medpay: 'No',
    atFaultDriverOtherPolicies: false,
    subroSetup: 'No',
    wageLoss: '$7,400',
    demandSentStatus: '4/5/25 - Demand for case updates',
    settlementAcceptedRelease: '7/15/25',
    checkReceived: '6/15/25',
    caseAge: 191,
    billingPacketSent: 'July 1, 2025',
    policyReportOrdered: 'July 10, 2025',
    totalCurrentBills: '$1,246',
    menuItems: menuItems,
  },
  {
    id: '2',
    caseNumber: '#2025-002',
    status: {
      text: 'Final Offer Received',
      color: 'var(--success)',
    },
    clientName: 'Martin, Samuel',
    primaryPhone: '(213) 987-6543',
    momsPhone: '(213) 555-1234',
    email: 'samuel.martin@email.com',
    casePlan: 'Response framework for intersection incident resolution',
    bigPolicy: false,
    bigInjury: true,
    injuryDescription: 'Wrist fracture, elbow sprain',
    clientStatusDetails: 'Awaiting orthopedic review for ongoing treatment',
    lorSent: [
      { date: '2/15/25', event: 'MedPay - State Farm', status: 'John Smith Policy' },
      { date: '2/20/25', event: 'Med Recs Ordered', status: 'Complete' },
      { date: '2/25/25', event: 'Demand Sent', status: 'Negotiating w/ State Farm' },
      { date: '3/10/25', event: 'Offer Accepted', status: 'Settlement Reached' },
      { date: '3/15/25', event: 'Check Received', status: 'Deposited' }
    ],
    medRecsOrdered: {
      someOrdered: false,
      allOrdered: true,
      allOrderedDate: '3/1/25'
    },
    liabilityLimits: {
      wasInCar: true,
      insurances: ['State Farm - $100k'],
      UmbrellaExcess: 'Yes - $1M umbrella'
    },
    clientUIMlimits: 'Progressive: $250,000',
    residentUMUIMLimits: 'Yes - $25,000',
    medpay: 'No',
    atFaultDriverOtherPolicies: true,
    subroSetup: '$5,800',
    wageLoss: '$3,200',
    demandSentStatus: '6/20/25 - Final demand package sent',
    settlementAcceptedRelease: '8/15/25',
    checkReceived: '8/20/25',
    caseAge: 145,
    billingPacketSent: 'June 15, 2025',
    policyReportOrdered: 'June 20, 2025',
    totalCurrentBills: '$8,450',
    menuItems: menuItems,
  },
  {
    id: '3',
    caseNumber: '#2025-003',
    status: {
      text: 'Awaiting Settlement Hearing',
      color: 'var(--orange)',
    },
    clientName: 'Johnson, Sarah',
    primaryPhone: '(555) 123-4567',
    momsPhone: '(555) 987-6543',
    email: 'sarah.johnson@email.com',
    casePlan: 'Highway collision case with multiple injuries',
    bigPolicy: true,
    bigInjury: true,
    injuryDescription: 'Multiple fractures, head trauma',
    clientStatusDetails: 'Scheduled for settlement conference next month',
    lorSent: [
      { date: '3/10/25', event: 'MedPay - Allstate', status: 'Mike Wilson Policy' },
      { date: '3/15/25', event: 'Med Recs Ordered', status: 'Complete' },
      { date: '3/20/25', event: 'Demand Sent', status: 'Negotiating w/ Allstate' },
      { date: '3/25/25', event: 'Offer Received', status: 'Under Review' }
    ],
    medRecsOrdered: {
      someOrdered: false,
      allOrdered: true,
      allOrderedDate: '4/15/25'
    },
    liabilityLimits: {
      wasInCar: true,
      insurances: ['Allstate - $500k', 'USAA - $250k'],
      UmbrellaExcess: 'Yes - $5M umbrella'
    },
    clientUIMlimits: 'Geico: $1,000,000',
    residentUMUIMLimits: 'Yes - $50,000',
    medpay: 'Medical $5,000',
    atFaultDriverOtherPolicies: true,
    subroSetup: '$15,600',
    wageLoss: '$8,900',
    demandSentStatus: '7/1/25 - Comprehensive demand package',
    settlementAcceptedRelease: 'Pending',
    checkReceived: 'Pending',
    caseAge: 98,
    billingPacketSent: 'June 25, 2025',
    policyReportOrdered: 'July 1, 2025',
    totalCurrentBills: '$45,200',
    menuItems: menuItems,
  },
  {
    id: '4',
    caseNumber: '#2025-004',
    status: {
      text: 'Finished Case',
      color: 'var(--middle-grey)',
    },
    clientName: 'Williams, David',
    primaryPhone: '(312) 555-7890',
    momsPhone: '(312) 555-2468',
    email: 'david.williams@email.com',
    casePlan: 'Rear-end collision with property damage',
    bigPolicy: false,
    bigInjury: false,
    injuryDescription: 'Neck strain, back pain',
    clientStatusDetails: 'Case closed - settlement completed',
    lorSent: [
      { date: '1/5/25', event: 'MedPay - Farmers', status: 'Lisa Brown Policy' },
      { date: '1/10/25', event: 'Med Recs Ordered', status: 'Complete' },
      { date: '1/15/25', event: 'Demand Sent', status: 'Negotiating w/ Farmers' },
      { date: '1/20/25', event: 'Offer Accepted', status: 'Settlement Reached' },
      { date: '1/25/25', event: 'Check Received', status: 'Deposited' }
    ],
    medRecsOrdered: {
      someOrdered: false,
      allOrdered: true,
      allOrderedDate: '2/1/25'
    },
    liabilityLimits: {
      wasInCar: false,
      insurances: ['Farmers - $25k'],
      UmbrellaExcess: 'No'
    },
    clientUIMlimits: 'None',
    residentUMUIMLimits: 'No',
    medpay: 'Medical $500',
    atFaultDriverOtherPolicies: false,
    subroSetup: '$1,200',
    wageLoss: '$800',
    demandSentStatus: '3/15/25 - Initial demand sent',
    settlementAcceptedRelease: '5/20/25',
    checkReceived: '5/25/25',
    caseAge: 245,
    billingPacketSent: 'March 10, 2025',
    policyReportOrdered: 'March 15, 2025',
    totalCurrentBills: '$3,200',
    menuItems: menuItems,
  },
  {
    id: '5',
    caseNumber: '#2025-005',
    status: {
      text: 'Respond',
      color: 'var(--orange)',
    },
    clientName: 'Davis, Jennifer',
    primaryPhone: '(714) 555-1357',
    momsPhone: '(714) 555-2468',
    email: 'jennifer.davis@email.com',
    casePlan: 'Pedestrian accident with significant injuries',
    bigPolicy: true,
    bigInjury: true,
    injuryDescription: 'Leg fractures, internal injuries',
    clientStatusDetails: 'Awaiting response from insurance adjuster',
    lorSent: [
      { date: '4/20/25', event: 'MedPay - USAA', status: 'Robert Taylor Policy' },
      { date: '4/25/25', event: 'Med Recs Ordered', status: 'Partial' },
      { date: '4/30/25', event: 'Demand Sent', status: 'Awaiting Response' }
    ],
    medRecsOrdered: {
      someOrdered: true,
      allOrdered: false,
      allOrderedDate: '5/10/25'
    },
    liabilityLimits: {
      wasInCar: true,
      insurances: ['USAA - $300k', 'Geico - $150k'],
      UmbrellaExcess: 'Yes - $2M umbrella'
    },
    clientUIMlimits: 'Progressive: $750,000',
    residentUMUIMLimits: 'Yes - $30,000',
    medpay: 'Medical $2,500',
    atFaultDriverOtherPolicies: false,
    subroSetup: '$8,400',
    wageLoss: '$12,600',
    demandSentStatus: '6/30/25 - Response required within 30 days',
    settlementAcceptedRelease: 'Pending',
    checkReceived: 'Pending',
    caseAge: 67,
    billingPacketSent: 'June 15, 2025',
    policyReportOrdered: 'June 20, 2025',
    totalCurrentBills: '$28,900',
    menuItems: menuItems,
  },
  {
    id: '6',
    caseNumber: '#2025-006',
    status: {
      text: 'No Offer 30+',
      color: 'var(--warning)',
    },
    clientName: 'Anderson, Michael',
    primaryPhone: '(305) 555-9876',
    momsPhone: '(305) 555-5432',
    email: 'michael.anderson@email.com',
    casePlan: 'Motorcycle accident with severe injuries',
    bigPolicy: true,
    bigInjury: true,
    injuryDescription: 'Multiple fractures, spinal injury',
    clientStatusDetails: 'No response from insurance after 30+ days',
    lorSent: [
      { date: '2/28/25', event: 'MedPay - Liberty Mutual', status: 'Chris Lee Policy' },
      { date: '3/5/25', event: 'Med Recs Ordered', status: 'Complete' },
      { date: '3/10/25', event: 'Demand Sent', status: 'Negotiating w/ Liberty Mutual' },
      { date: '3/15/25', event: 'Offer Received', status: 'Under Review' }
    ],
    medRecsOrdered: {
      someOrdered: false,
      allOrdered: true,
      allOrderedDate: '3/15/25'
    },
    liabilityLimits: {
      wasInCar: true,
      insurances: ['Liberty Mutual - $100k'],
      UmbrellaExcess: 'Pending evaluation'
    },
    clientUIMlimits: 'State Farm: $500,000',
    residentUMUIMLimits: 'Yes - $15,000',
    medpay: 'Medical $3,000',
    atFaultDriverOtherPolicies: true,
    subroSetup: '$12,800',
    wageLoss: '$18,400',
    demandSentStatus: '5/1/25 - No response after 30 days',
    settlementAcceptedRelease: 'Pending',
    checkReceived: 'Pending',
    caseAge: 156,
    billingPacketSent: 'April 20, 2025',
    policyReportOrdered: 'April 25, 2025',
    totalCurrentBills: '$67,500',
    menuItems: menuItems,
  },
  {
    id: '7',
    caseNumber: '#2025-007',
    status: {
      text: 'Signed Release',
      color: 'var(--purple)',
    },
    clientName: 'Taylor, Lisa',
    primaryPhone: '(503) 555-2468',
    momsPhone: '(503) 555-1357',
    email: 'lisa.taylor@email.com',
    casePlan: 'T-bone collision with ongoing treatment',
    bigPolicy: false,
    bigInjury: true,
    injuryDescription: 'Rib fractures, concussion',
    clientStatusDetails: 'Release signed and returned to adjuster',
    lorSent: [
      { date: '3/5/25', event: 'MedPay - Nationwide', status: 'Alex Chen Policy' },
      { date: '3/10/25', event: 'Med Recs Ordered', status: 'Complete' },
      { date: '3/15/25', event: 'Demand Sent', status: 'Negotiating w/ Nationwide' },
      { date: '3/20/25', event: 'Offer Accepted', status: 'Settlement Reached' },
      { date: '3/25/25', event: 'Check Received', status: 'Deposited' }
    ],
    medRecsOrdered: {
      someOrdered: false,
      allOrdered: true,
      allOrderedDate: '4/1/25'
    },
    liabilityLimits: {
      wasInCar: false,
      insurances: ['Nationwide - $50k'],
      UmbrellaExcess: 'No'
    },
    clientUIMlimits: 'Geico: $100,000',
    residentUMUIMLimits: 'No',
    medpay: 'Medical $800',
    atFaultDriverOtherPolicies: false,
    subroSetup: '$2,100',
    wageLoss: '$4,200',
    demandSentStatus: '6/10/25 - Settlement reached',
    settlementAcceptedRelease: '7/15/25',
    checkReceived: '7/20/25',
    caseAge: 134,
    billingPacketSent: 'May 30, 2025',
    policyReportOrdered: 'June 5, 2025',
    totalCurrentBills: '$12,300',
    menuItems: menuItems,
  },
  {
    id: '8',
    caseNumber: '#2025-008',
    status: {
      text: 'Check Pending',
      color: 'var(--primary-color)',
    },
    clientName: 'Wilson, Robert',
    primaryPhone: '(206) 555-3691',
    momsPhone: '(206) 555-7410',
    email: 'robert.wilson@email.com',
    casePlan: 'Intersection accident with property damage',
    bigPolicy: true,
    bigInjury: false,
    injuryDescription: 'Soft tissue injuries, whiplash',
    clientStatusDetails: 'Settlement accepted, check in transit',
    lorSent: [
      { date: '4/15/25', event: 'MedPay - Travelers', status: 'Maria Garcia Policy' },
      { date: '4/20/25', event: 'Med Recs Ordered', status: 'Partial' },
      { date: '4/25/25', event: 'Demand Sent', status: 'Awaiting Response' }
    ],
    medRecsOrdered: {
      someOrdered: false,
      allOrdered: true,
      allOrderedDate: '5/1/25'
    },
    liabilityLimits: {
      wasInCar: true,
      insurances: ['Travelers - $200k'],
      UmbrellaExcess: 'Yes - $1M umbrella'
    },
    clientUIMlimits: 'Allstate: $300,000',
    residentUMUIMLimits: 'Yes - $20,000',
    medpay: 'Medical $1,500',
    atFaultDriverOtherPolicies: true,
    subroSetup: '$4,600',
    wageLoss: '$6,800',
    demandSentStatus: '7/25/25 - Settlement accepted',
    settlementAcceptedRelease: '8/1/25',
    checkReceived: 'Pending',
    caseAge: 89,
    billingPacketSent: 'July 20, 2025',
    policyReportOrdered: 'July 25, 2025',
    totalCurrentBills: '$19,700',
    menuItems: menuItems,
  },
];
    
export const AllStatuses: Story = {
  args: {
    cases: sampleCases,
  },
};

